package yitgogo.consumer.tools;

public interface Parameters {

    public String CACHE_KEY_COOKIE = "CACHE_KEY_COOKIE";
    public String CACHE_KEY_COOKIE_MONEY = "CACHE_KEY_COOKIE_MONEY";
    public String CACHE_KEY_STORE_TYPE = "CACHE_KEY_STORE_TYPE";
    public String CACHE_KEY_STORE_AREA = "CACHE_KEY_STORE_AREA";
    public String CACHE_KEY_STORE_JSONSTRING = "CACHE_KEY_STORE_JSONSTRING";
    public String CACHE_KEY_CAR = "CACHE_KEY_CAR";
    public String CACHE_KEY_CAR_LOCAL = "CACHE_KEY_CAR_LOCAL";
    public String CACHE_KEY_ORDER_PRODUCT = "CACHE_KEY_ORDER_PRODUCT";
    public String CACHE_KEY_MONEY_SN = "CACHE_KEY_MONEY_SN";
    public String CACHE_KEY_USER_JSON = "CACHE_KEY_USER_JSON";
    public String CACHE_KEY_USER_PASSWORD = "CACHE_KEY_USER_PASSWORD";
    public String CACHE_KEY_SUNING_SIGNATURE = "CACHE_KEY_SUNING_SIGNATURE";

    public int CACHE_VALUE_STORE_TYPE_LOCATED = 0;
    public int CACHE_VALUE_STORE_TYPE_SELECTED = 1;

    public String CONSTANT_LBS_AK = "rzj51UaclRiYTPIDkj5NnbG5";
    public String CONSTANT_LBS_TABLE = "96314";
    public String CONSTANT_RMB = "¥";
    String CACHE_KEY_SUNING_AREAS = "CACHE_KEY_SUNING_AREAS";
}
